spring.datasource.url=jdbc:postgresql://localhost:5432/eshop
spring.datasource.username=emc
spring.datasource.password=emc
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE